apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldk8
spec:
  selector:
    matchLabels:
      app: helloworldk8
  template:
    metadata:
      labels:
        app: helloworldk8
    spec:
      containers:
      - name: helloworldk8
        image: pluralsightmicroservicesregistry.azurecr.io/helloworldk8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldk8
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: helloworldk8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpclient
spec:
  selector:
    matchLabels:
      app: httpclient
  template:
    metadata:
      labels:
        app: httpclient
    spec:
      containers:
      - name: httpclient
        image: pluralsightmicroservicesregistry.azurecr.io/pluralsightmoviestoreclient
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pluralsightmoviestoreclient
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pluralsightmoviestoreclient